# ======================================== InitConfiguration ========================================
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  ttl: 24h0m0s                                                # Время жизни токена
  usages:
  - signing
  - authentication
localAPIEndpoint:
  advertiseAddress: 192.168.2.211                             # IP первой Control ноды 
  bindPort: 6443                                              # (6443) Порт на первой Control ноде
nodeRegistration:
  criSocket: "unix:///var/run/containerd/containerd.sock"
  imagePullPolicy: IfNotPresent
  name: k8s-rhel-master1.fillswim.local                       # Имя первой Control plane ноды
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane                # node-role.kubernetes.io/master - deprecated

# ====================================== ClusterConfiguration =======================================
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
certificatesDir: /etc/kubernetes/pki            # Где будут находиться сертификаты
clusterName: cluster.local                      # Доменное имя кластера
controllerManager: {}
dns: {}
etcd:
  local:
    dataDir: /var/lib/etcd                      # Где хранятся данные etcd
imageRepository: "registry.k8s.io"              # Откуда будут скачиться образы
apiServer:
  timeoutForControlPlane: 4m0s
  extraArgs:
    authorization-mode: Node,RBAC
    bind-address: 0.0.0.0
    service-cluster-ip-range: "10.96.0.0/16"    # Сеть для сервисов
    service-node-port-range: 30000-32767        # Сеть для сервисов NodePort
kubernetesVersion: "1.28.3"
controlPlaneEndpoint: 192.168.2.211:6443        # Кластерный IP на HAProxy и кластерный порт (куда будут обращаться остальные ноды при добавлении)
networking:
  dnsDomain: cluster.local
  podSubnet: "10.244.0.0/24"                    # Сеть для подов
  serviceSubnet: "10.96.0.0/16"                 # Сеть для сервисов
scheduler: {}

# ===================================== KubeProxyConfiguration ======================================
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
bindAddress: 0.0.0.0
clusterCIDR: "10.244.0.0/24"
ipvs:
  strictARP: True
mode: ipvs

# ====================================== KubeletConfiguration =======================================
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
clusterDNS:                                     # Нужно установить на каждой ноде кластера
- 10.96.0.10
systemReserved:
  memory: 512Mi
  cpu: 500m
  ephemeral-storage: 2Gi
# Default: "10Mi"
containerLogMaxSize: 1Mi
# Default: 5
containerLogMaxFiles: 3