---
apiVersion: apps/v1

# kubectl apply -f Longhorn/Test_PVC/02-MyGifService-Deployment-PVC.yaml
# kubectl delete -f Longhorn/Test_PVC/02-MyGifService-Deployment-PVC.yaml

kind: Deployment
metadata:                                     ### Описание деплоймента
  name: mygifservice-deployment               # Название деплоймента
  namespace: volumes-sample
  labels:                                     # Лейбл деплоймента
    app: mygifservice-app

spec:                                         ### Спецификация
  replicas: 3                                 # Т.к. в PV и PVC AccessModes: ReadWriteMany (Volume том может быть смонтирован к множеству подов в режиме чтения и записи) 

  selector:
    matchLabels:                              # С какими лейблами подов будет работать деплоймент
      app: mygifservice-app
      project: mygifservice-project

  template:                                   ### Описание подов
    metadata:                                 ## Описание пода № 1
      labels:                                 # Лейблы подов Должны совпадать с selector
        app: mygifservice-app
        project: mygifservice-project
    spec:
      containers:                             # Какие контейнеры будут запускаться в подах
      - name: mygifservice-container
        image: fillswim/mygifservice:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /mnt/longhorn             # куда монтируется PVC внутри контейнера
            name: claim-volume
      volumes:
        - name: claim-volume
          persistentVolumeClaim:
            claimName: claim-longhorn-pvc        # наименование монтируемого PVC
