# ======================================== Deployment ========================================
apiVersion: apps/v1
kind: Deployment

metadata:
  name: mygifservice-deployment
  labels:
    app: mygifservice-deployment-app
    
spec:
  replicas: 3

  selector:
    matchLabels:
      app: mygifservice-pod
      project: mygifservice-project
      
  template:
    metadata:
      labels:
        app: mygifservice-pod
        project: mygifservice-project
    spec:
      containers:
      - name: mygifservice-container
        image: fillswim/mygifservice:latest
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080               # Открытый порт на поде

# ========================================== Service =========================================
---
apiVersion: v1
kind: Service

metadata:
  name: mygifservice-service
  labels:
    env: prod

spec:
  type: LoadBalancer
  # Определить адрес для LB (http://192.168.2.217:8080/swagger-ui/index.html)
  # loadBalancerIP: 192.168.2.217
  selector:
    app: mygifservice-pod
    project: mygifservice-project
  ports:
  - port: 8080                            # Открытый порт на LB
    targetPort: 8080                      # Открытый порт на поде