apiVersion: apps/v1
kind: Deployment

metadata:                                     ### Описание деплоймента
  name: mygifservice-deployment               # Название деплоймента
  labels:                                     # Лейбл деплоймента
    app: mygifservice-deployment-app
    
spec:                                         ### Спецификация
  replicas: 3                                 # Количество реплик пода

  selector:
    matchLabels:                              # С какими лейблами подов будет работать деплоймент
      app: mygifservice-pod
      project: mygifservice-project
      
  template:                                   ### Описание подов
    metadata:                                 ## Описание пода № 1
      labels:                                 # Лейблы подов Должны совпадать с selector
        app: mygifservice-pod                 #! Сервис будет искать поды с этими лейблы, чтобы на них распределять трафик
        project: mygifservice-project
    spec:
      containers:                             # Какие контейнеры будут запускаться в подах
      - name: mygifservice-container
        image: fillswim/mygifservice:latest   # Можно менять версии (Является япеременной в Helm Chart)
        resources:
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080                 #!! Порт на поде

---
apiVersion: v1                                ### Описание Сервиса
kind: Service

metadata:
  name: mygifservice-service                  # Имя сервиса
  labels:                                     # Лейблы сервиса
    env: prod
    owner: OlegFilatov

spec:
  type: LoadBalancer                          # Тип сервиса
  # loadBalancerIP: 192.168.2.151               # По какому адресу будет доступно приложение (http://192.168.2.151:8080/swagger-ui/index.html)
  selector:
    app: mygifservice-pod                     #! На поды с какими лейблами будет работать сервис, распространять трафик
    project: mygifservice-project
  ports:
  - port: 8080                                # Какой на Load Balancer будет открыть порт
    targetPort: 8080                          #!! Порт на поде